import json
import sys
from pathlib import Path
from sqlmodel import Session
from database import engine
from models import College, Department, Course, Section
from schemas import SectionData

# Ensure Python can find your models and schemas from the root directory
sys.path.append(str(Path(__file__).resolve().parent.parent))

def load_data_to_db(json_file_path: str | Path):
    path = Path(json_file_path)
    
    if not path.exists():
        print(f"Error: Could not find {path.name}")
        return

    print(f"Reading {path.name}...")
    with open(path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    # 1. In-Memory Storage (Prevents asking the database if a college exists 10,000 times)
    unique_colleges = {}
    unique_departments = {}
    unique_courses = {}
    sections_to_insert = []

    print("Processing and deduplicating records in memory...")
    
    # 2. Parse and Sort
    for raw_item in raw_data:
        # Pass the raw dictionary through Pydantic to get clean, typed data
        try:
            item = SectionData(**raw_item)
        except Exception as e:
            # Skip invalid rows if they slipped through
            print(f"Skipping invalid row: {e}")
            continue

        # Build Unique Colleges
        if item.college_id not in unique_colleges:
            unique_colleges[item.college_id] = College(
                id=item.college_id, 
                name=item.college_name  # Ensure you map this alias in schemas.py
            )

        # Build Unique Departments
        if item.dept_id not in unique_departments:
            unique_departments[item.dept_id] = Department(
                id=item.dept_id,
                name=item.dept_name,
                college_id=item.college_id
            )

        # Build Unique Courses
        if item.course_id not in unique_courses:
            unique_courses[item.course_id] = Course(
                id=item.course_id,
                title=item.course_title,
                hours=item.hours,
                department_id=item.dept_id
            )

        # Build Sections (These are always unique by CRN)
        sections_to_insert.append(
            Section(
                crn=item.crn,
                course_id=item.course_id,
                teacher=item.teacher,
                gender=item.gender.value,
                start_time=item.start_time,
                end_time=item.end_time,
                days=item.days
            )
        )

    # 3. Bulk Database Insertion
    print("Committing to the database...")
    
    with Session(engine) as session:
        # Must be committed in hierarchical order due to Foreign Keys
        
        print(f"   -> Merging {len(unique_colleges)} Colleges...")
        for college in unique_colleges.values():
            session.merge(college)
        session.commit()

        print(f"   -> Merging {len(unique_departments)} Departments...")
        for dept in unique_departments.values():
            session.merge(dept)
        session.commit()

        print(f"   -> Merging {len(unique_courses)} Courses...")
        for course in unique_courses.values():
            session.merge(course)
        session.commit()

        print(f"   -> Merging {len(sections_to_insert)} Sections...")
        for section in sections_to_insert:
            session.merge(section)
        session.commit()

    print("Database load complete!")

if __name__ == "__main__":    
    # Point to the massive JSON file generated by fetcher.py
    data_file = Path(__file__).parent / "data" / "university_courses_data.json"
    
    # Execute
    load_data_to_db(data_file)