export const uiText = {
  appTitle: 'جدولني - KFU',
  selectGender: 'اختر القسم',
  male: 'طلاب',
  female: 'طالبات',
  searchPlaceholder: 'ابحث عن مقرر بالرقم المرجعي (مثل: \u200E0921-111)',
  wantedCourses: 'المقررات المختارة',
  generate: 'إنشاء الجداول',
  supportedColleges: 'الكليات المدعومة',
  generating: 'جاري إنشاء الجداول...',
  back: 'رجوع',
  search: '...بحث',
  editCourses: 'تعديل المواد',
  scheduleOf: 'الجدول {current} من {total}',
  dayOff: 'يوم إجازة',
  instructor: 'الدكتور',
  crn: 'الرقم المرجعي',
  noResults: 'لم يتم العثور على جداول متوافقة',
  noFilters: 'لا توجد جداول تطابق الفلاتر المحددة',
  clearFilters: 'مسح الفلاتر',
  networkError: 'خطأ في الشبكة',
  retry: 'إعادة المحاولة',
  noSections: 'لا توجد شعب متاحة لهذا المقرر',
  largeResults: 'عدد الجداول كبير، قد يستغرق التحميل وقتاً',
  removeCourse: 'إزالة',
  time: 'الوقت',
  sun: 'الأحد',
  mon: 'الاثنين',
  tue: 'الثلاثاء',
  wed: 'الأربعاء',
  thu: 'الخميس',
  theory: 'نظري',
  practical: 'عملي',
  next: 'التالي',
  previous: 'السابق',
  theme: 'المظهر',
  availability: 'الحالة',
  all: 'الكل',
  availableOnly: 'متاحة فقط',
  scheduleCount: 'تم العثور على {found} جدول، يتم عرض {displayed} منهم',
  connecting: 'جاري الاتصال بالخادم...',
  serverWakingUp: 'الخادم يستيقظ من الخمول...',
  serverWakingUpDesc: 'يتم إيقاف تشغيل الخادم مؤقتاً عند عدم الاستعمال لتوفير الموارد. يستغرق بدء التشغيل حوالي 50 ثانية. شكراً لانتظارك!',
  estimatedTime: 'الوقت المتبقي المقدر: {seconds} ثانية',
  noCourses: 'لم يتم العثور على مقررات',
  footer: {
    lastUpdated: 'آخر تحديث',
    developedBy: 'تم التطوير بواسطة هادي لطلاب جامعة الملك فيصل',
    github: 'GitHub',
    contactTelegram: 'تواصل عبر تليجرام',
    unknown: 'غير معروف'
  },
}
